### ISSUE TITLE
构建教程？

### ISSUE THREAD

**Issue by LXY1226** [roj234/rojlib#1]
*新年快乐*
首先，感谢大佬能写出这样一个感觉很有用的il mod，虽然因为奇怪的冲突并不能很好的在我的设备中启动...
所以，我想请教如何编译这个项目
注：mcbbs中的相关帖子已经归档不能访问

再次，*新年快乐*
*祝高考顺利*

**Comment by roj234** [comment]
啊，这么久没看，居然有issue...

编译:
编译的话，啊，mcbbs关贴啦
https://pan.baidu.com/s/173yVof-Qmsdf6Bn73Evz7g
9pbx
你可以去这里下载FMD编译好的版本，然后解压1.12.2版本的离线数据到同一个文件夹
最新版本是1.5.7 我刚刚上传,因为实在没人
在FMD-xxx.zip中还含有一些介绍

然后用FMD新建一个名字叫implib的project
把本项目克隆到implib/java目录下
没错，没有资源文件，因为，嗯，有些东西不适合，我也懒得做gitignore

忠告：
我很久没有维护它了，我只能保证编译通过，MC可以开启
其他不做保证...
比如前几天才修复了一个配置文件会自动回复默认值的bug
这种东西不知道还有多少

要继续开发implib至少要等我写出一个javac，对于jdk自带的javac我受够了
即使会导致模板膨胀啥的，基本类型的泛型我支持定了
还有编译速度，慢的死，我自己写一个起码可以优化了，或者知道慢在哪里...

若是FMD有bug，我感谢你的PR，或者截图也可以...
比如它的下载功能，我基本就没测试过...
因为forge给自己maven加了密码，若是有破解方法，大概是有的。不然它们自己怎么下
但是我没需求，比如1.17我也不打算搞了
有空会去做的
不过又要上学，又有其他的代码，今年能做好就谢天谢地了

**Comment by roj234** [comment]
资源文件从老版本的jar里拿，下载地址还在mcmod.cn有备份
这个mod的优化起源说起来可笑，就是因为bbs版规不允许发布无功能的纯前置mod

**Comment by roj234** [comment]
两年过去了，终于有空搞【workflow自动构建】了，可惜物是人非，连mcbbs都没了，我也不做模组了
但是既然这个issue还开在这里，我就留念一下吧，哎

**Comment by LXY1226** [comment]
mcbbs没了也太乐了(

留念留念
