### ISSUE TITLE
初学java看完写不出来东西怎么办

### ISSUE THREAD

**Issue by gitLSCS** [roj234/rojlib#3]
从小站过来的  你这不用编译器都能写代码 算不算有天赋

**Comment by roj234** [comment]
不用编译器都能写代码?
即使FMD也要安装JDK的，虽然我有在做javac但是目前为止只能解析方法和字段的定义，甚至不支持inner class。。。
主要是强类型和弱类型确实区别很大
js naive一点还可以搞搞低效实现
这个就等着灵感了
当时js的运算符优先级就是睡觉的时候想到的

**Comment by roj234** [comment]
以及，你想写什么？ 我感觉我这库不适合初学者（实际上啥库，除了大家都觉得是best-practice的，都不适合吧）
不过有的地方我就过早优化了，还有啥未经测试就提交，等等
还有几个星期可能就会breaking change之前一些方法都没用了
