### ISSUE TITLE
正常的游戏加了mod后不能启动了

### ISSUE THREAD

**Issue by chenming0v0** [roj234/rojlib#6]
日志：https://mclo.gs/AHDDNZt
没有crash-report文件
表现为无法跳出mc游戏窗口
我加了“-Xverify:none”虚拟机参数了
![image](https://github.com/roj234/rojlib/assets/122023652/c44c554e-0453-41c4-a150-58e3c94b4c46)
mod版本为：ImpLib-1.1.5RC2

**Comment by chenming0v0** [comment]
![Uploading image.png…]()
emmmm.....

**Comment by chenming0v0** [comment]
![image](https://github.com/roj234/rojlib/assets/122023652/d0ba0f32-a23a-49b4-b495-01964ed28616)
emmmm......
不懂

**Comment by roj234** [comment]
模组已经不开发了（如果你确实想用，使用早一点的版本），不过如果它还开发的话，这几天更新的NiximSystem 2.0版本应该能修复这个问题

**Comment by chenming0v0** [comment]
啊？请问那个版本比较稳定并且支持匠魂与AE

**Comment by chenming0v0** [comment]
或许在啥时候可以完成您说的“更新的NiximSystem 2.0”

**Comment by roj234** [comment]
> 或许在啥时候可以完成您说的“更新的NiximSystem 2.0”

好消息这个项目更新了(看commit)，坏消息是模组部分不更新了，我已经大概半年没玩MC了
至于匠魂和AE？1.1.0应该可以

**Comment by chenming0v0** [comment]
好的，我试试1.1.0吧

**Comment by chenming0v0** [comment]
好吧，在测试了1.1.0后还是这样
![image](https://github.com/roj234/rojlib/assets/122023652/65f31ff2-19f3-4611-a726-ce40169f200d)

**Comment by chenming0v0** [comment]
https://mclo.gs/8p6r87B

**Comment by roj234** [comment]
那多半是和哪个mod冲突了，Nixim这东西你也能看出来就是和Mixin对着干的——有的时候人就是想做一套代码都是自己写的工具
然后代价就是兼容性很差，特别是和功能极为类似的Mixin（毕竟它设计时，让不同模组协作的方式，和我的完全不同）

**Comment by chenming0v0** [comment]
那好吧,我去看看别的优化mod

**Comment by roj234** [comment]
真是不好意思（希望在你听起来不是阴阳怪气，这年头说个话都小心翼翼的了

**Comment by chenming0v0** [comment]
谔谔，看起来确实有点像阴阳怪气好吧，我去忙别的了
